apiVersion: apps/v1
kind: Deployment
metadata:
  name: razee-app
  labels:
    app: razee
spec:
  selector:
    matchLabels:
      app: razee
  template:
    metadata:
      labels:
        app: razee
    spec:
      containers:
      - image: nginx
        name: razee-app
 
